package DataAccess;

import java.io.*;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Reads clustering-resulting data set generated by BrizziB implementation
 */
class BrizziBReader extends DatasetReader{
    private File[] files = null;

    /**
     * @param filenames an array of file path of the outputs of BrizziB's implementation
     */
    BrizziBReader(String[] filenames){
        files = new File[filenames.length];
        for(int i = 0; i < filenames.length; ++i)
            files[i] = new File(filenames[i]);
    }

    /**
     * Default constructor. You need to call setUp method after.
     */
    BrizziBReader(){}

    /**
     * @param filenames an array of file path of the outputs of BrizziB's implementation
     */
    @Override
    public void setUp(String[] filenames){
        files = new File[filenames.length];
        for(int i = 0; i < filenames.length; ++i)
            files[i] = new File(filenames[i]);
    }

    public void readDataset() throws IOException {
        int cluster = 0;
        for(File f : files){
            try(BufferedReader reader = new BufferedReader(new FileReader(f))) {

                final Pattern pattern = Pattern.compile("-?\\d+(\\.\\d+)?(\\w[-\\+]?\\d+)?\\s");
                final int group = 0;

                String line;
                while ((line = reader.readLine()) != null) {
                    if(!line.equals("")) {
                        if (!line.contains("\t"))
                            ++cluster;
                        else {
                            if (line.length() > 1)
                                dataset.put(parseSpatialAttrs(line, pattern, group), cluster);
                        }
                    }
                }
            }
        }
    }

    public static void main(String[] args) throws IOException {
        String[] filenames = {"/home/data/Dropbox/Tesi/CLUSTERING/working_implem/BrizziB/KFreqMoment/2d3c_test3/output/iteraz_3 (copia)/part-r-00000",
                "/home/data/Dropbox/Tesi/CLUSTERING/working_implem/BrizziB/KFreqMoment/2d3c_test3/output/iteraz_3 (copia)/part-r-00001",
                "/home/data/Dropbox/Tesi/CLUSTERING/working_implem/BrizziB/KFreqMoment/2d3c_test3/output/iteraz_3 (copia)/part-r-00002"};
        DatasetReader reader = new BrizziBReader(filenames);

        reader.readDataset();

        Map<String, Integer> ds = reader.getDataset();
    }

}
