package DataAccess;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Reads clustering-resulting data set generated by Yhfyhf implementation
 */
class YhfyhfReader extends DatasetReader {
    private File file;

    /**
     * Default constructor. You need to call setUp method after.
     */
    YhfyhfReader(){}

    /**
     * @param filenames a single object array containing the file path of Yhfyhf implementation's output
     */
    @Override
    public void setUp(String[] filenames) {
        file = new File(filenames[0]);
    }

    @Override
    public void readDataset() throws IOException {
        try(BufferedReader reader = new BufferedReader(new FileReader(file))){
            final Pattern clusterPattern = Pattern.compile("\\d+\\t");
            final Pattern pointPattern = Pattern.compile("(\\d+\\t)?(-?\\d+(\\.\\d+)?(\\w[-\\+]?\\d+)?\\s?)");
            final int clusterGroup = 0;
            final int pointGroup = 2;

            String line;
            while((line = reader.readLine()) != null){
                Matcher matcher = clusterPattern.matcher(line);
                if(matcher.find()){
                    int cluster = Integer.parseInt(matcher.group(clusterGroup).trim());
                    cluster++;
                    dataset.put(parseSpatialAttrs(line, pointPattern, pointGroup), cluster);
                }
            }
        }
    }
}
