package DataAccess;

import java.io.*;
import java.util.regex.Pattern;

/**
 * Reads clustering-resulting data set generated by BrizziB implementation
 */
class BrizziBReader extends DatasetReader {
    private File[] files = null;

    /**
     * @param filenames an array of file path of the outputs of BrizziB's implementation
     */
    BrizziBReader(String[] filenames){
        files = new File[filenames.length];
        for(int i = 0; i < filenames.length; ++i)
            files[i] = new File(filenames[i]);
    }

    BrizziBReader(){}

    /**
     * @param filenames an array of file path of the outputs of BrizziB's implementation
     */
    @Override
    public void setUp(String[] filenames){
        files = new File[filenames.length];
        for(int i = 0; i < filenames.length; ++i)
            files[i] = new File(filenames[i]);
    }

    @Override
    public void readDataset() throws IOException {
        if(files == null)
            throw new IllegalStateException("setUp should be called first.");
        int cluster = 0;
        for(File f : files){
            try(BufferedReader reader = new BufferedReader(new FileReader(f))) {

                final Pattern pattern = Pattern.compile("-?\\d+(\\.\\d+)?(\\w[-\\+]?\\d+)?\\s");
                final int group = 0;

                String line;
                while ((line = reader.readLine()) != null) {
                    if(!line.equals("")) {
                        if (!line.contains("\t"))
                            ++cluster;
                        else {
                            if (line.length() > 1) {
                                spectralAttrs.add(parseAttrs(line, pattern, group));
                                classes.add(cluster);
                            }
                        }
                    }
                }
            }
        }
    }

    /*
    public static void main(String[] args) throws IOException, Business.SilhouetteException.DifferentLengthException, Business.SilhouetteException.EmptyDatasetException {
        String[] filenames = {"/home/data/Dropbox/Tesi/CLUSTERING/working_implem/BrizziB/KFreqMoment/2d3c_test3/output/iteraz_3(copia)/part-r-00000",
                "/home/data/Dropbox/Tesi/CLUSTERING/working_implem/BrizziB/KFreqMoment/2d3c_test3/output/iteraz_3(copia)/part-r-00001",
                "/home/data/Dropbox/Tesi/CLUSTERING/working_implem/BrizziB/KFreqMoment/2d3c_test3/output/iteraz_3(copia)/part-r-00002"};
        DataAccess.DatasetReader reader = new DataAccess.BrizziBReader(filenames);

        reader.readDataset();

        Business.SilhouetteCalculator sc = new Business.SilhouetteCalculator(reader.getAttrs(), reader.getClassAttrs());

        System.out.println(sc.silhouette());
    }*/
}
