package DataAccess;

import DataAccess.DatasetReader;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Reads clustering-resulting data set generated by Yhfyhf implementation
 */
class YhfyhfReader extends DatasetReader {
    private File file;

    /**
     * @param filename file path of Yhfyhf implementation's output
     */
    YhfyhfReader(String filename){
        file = new File(filename);
    }

    /**
     * Default constructor. You need to call setUp method after
     */
    YhfyhfReader(){}

    /**
     * @param filenames a single object array containing the file path of Yhfyhf implementation's output
     */
    @Override
    public void setUp(String[] filenames) {
        file = new File(filenames[0]);
    }

    @Override
    public void readDataset() throws IOException {
        if(file == null)
            throw new IllegalStateException("setUp should be called first.");
        try(BufferedReader reader = new BufferedReader(new FileReader(file))){
            final Pattern pattern = Pattern.compile("(\\d+\\t)?(-?\\d+(\\.\\d+)?(\\w[-\\+]?\\d+)?\\s?)");
            final int clusterGroup = 1;
            final int pointGroup = 2;

            String line;
            while((line = reader.readLine()) != null){
                Matcher matcher = pattern.matcher(line);
                if(matcher.find()){
                    int cluster = Integer.parseInt(matcher.group(clusterGroup).trim());
                    spectralAttrs.add(parseAttrs(line, pattern, pointGroup));
                    classes.add(++cluster);
                }
            }
        }
    }

    /*
    public static void main(String[] args) throws IOException {
        DataAccess.DatasetReader reader = new DataAccess.YhfyhfReader("/home/data/Dropbox/Tesi/CLUSTERING/working_implem/yhfyhf/KFreqMoment/2d5c_test2/output/2(copia)/part-r-00000");
        reader.readDataset();
        reader.getClassAttrs();
    }*/
}
